import type { Trip } from './types'

export const SAMPLE_TRIPS: Trip[] = [
  {
    id: 'sample-kopecek',
    title: 'Ráno na Svatý Kopeček',
    date: '2026-09-14',
    startPlace: 'Olomouc – centrum',
    endPlace: 'Svatý Kopeček',
    routeName: 'Město → Kopeček a zpět lesem',
    distanceKm: 28.4,
    durationMin: 98,
    elevationM: 310,
    avgSpeedKmh: null,
    notes:
      'Káva u baziliky, zpátky přes Chválkovice. Lehký protivítr na hrázi, jinak pohoda. Ideální nedělní tempo.',
    tags: ['silnice'],
    createdAt: '2026-09-14T07:40:00.000Z',
  },
  {
    id: 'sample-pomoravi',
    title: 'Gravel Litovelským Pomoravím',
    date: '2026-09-07',
    startPlace: 'Horka nad Moravou',
    endPlace: 'Litovel',
    routeName: 'Luční stezky podél Moravy',
    distanceKm: 46.2,
    durationMin: 175,
    elevationM: 180,
    avgSpeedKmh: null,
    notes:
      'Měkké úseky po dešti, ale krásné světlo v lužním lese. Občerstvení v Litovli, zpět vlakem. Gravel pneumatiky se vyplatily.',
    tags: ['gravel'],
    createdAt: '2026-09-07T08:15:00.000Z',
  },
  {
    id: 'sample-jeseniky',
    title: 'Červenohorské sedlo z Loučné',
    date: '2026-08-23',
    startPlace: 'Loučná nad Desnou',
    endPlace: 'Červenohorské sedlo',
    routeName: 'Stoupání silnicí, sjezd na Kouty',
    distanceKm: 38.7,
    durationMin: 168,
    elevationM: 820,
    avgSpeedKmh: null,
    notes:
      'Těžké nohy v posledních kilometrech, ale výhled z sedla stál za to. Sjezd opatrně — spousta motorek. V Koutech pivo a vlak.',
    tags: ['silnice', 'mtb'],
    createdAt: '2026-08-23T06:50:00.000Z',
  },
  {
    id: 'sample-bouzov',
    title: 'Za hradem Bouzov',
    date: '2026-08-10',
    startPlace: 'Loštice',
    endPlace: 'Bouzov',
    routeName: 'Silnice přes Měník a Bílou Lhotu',
    distanceKm: 52.1,
    durationMin: 188,
    elevationM: 640,
    avgSpeedKmh: null,
    notes:
      'Klasický výlet s partou. Oběd pod hradem, zpáteční cesta už v kroupách. Jeden defekt, jinak bez dramatu.',
    tags: ['silnice'],
    createdAt: '2026-08-10T09:05:00.000Z',
  },
  {
    id: 'sample-mtb',
    title: 'Kořeny nad Šternberkem',
    date: '2026-07-19',
    startPlace: 'Šternberk',
    endPlace: 'Šternberk',
    routeName: 'Okruh lesními cestami k Dalovu',
    distanceKm: 22.8,
    durationMin: 132,
    elevationM: 490,
    avgSpeedKmh: null,
    notes:
      'Technické sjezdy po dešti, hodně bláta. Skvělé singletracky nad městem. Příště sušší den a širší pláště.',
    tags: ['mtb'],
    createdAt: '2026-07-19T15:20:00.000Z',
  },
]
